create table swuser
(
	uid		BIGINT UNSIGNED		AUTO_INCREMENT PRIMARY KEY,
	ip		VARCHAR(20)		NOT NULL,
	port		VARCHAR(10)		NOT NULL
);

create table time
(
	tid		BIGINT UNSIGNED		AUTO_INCREMENT PRIMARY KEY,
	year		SMALLINT UNSIGNED,
	month		TINYINT UNSIGNED,
	day		TINYINT UNSIGNED,
	hour		TINYINT UNSIGNED,
	min		TINYINT UNSIGNED,
	sec		TINYINT UNSIGNED
);

create table dht
(
	dhtid		BIGINT UNSIGNED		AUTO_INCREMENT PRIMARY KEY,
	humidity_int	TINYINT UNSIGNED		NOT NULL,
	humidity_flt	TINYINT UNSIGNED		NOT NULL,
	temperature_int	TINYINT SIGNED		NOT NULL,
	temperature_flt	TINYINT UNSIGNED		NOT NULL,
	uid		BIGINT UNSIGNED		NOT NULL,
	tid		BIGINT UNSIGNED		NOT NULL,
	
	FOREIGN KEY(uid)
	REFERENCES swuser(uid) 
	ON UPDATE CASCADE ON DELETE CASCADE,
	
	FOREIGN KEY(tid)
	REFERENCES time(tid) 
	ON UPDATE CASCADE ON DELETE CASCADE
);

create table dd
(
	ddid		BIGINT UNSIGNED		AUTO_INCREMENT PRIMARY KEY,
	uid		BIGINT UNSIGNED		NOT NULL,
	tid		BIGINT UNSIGNED		NOT NULL,

	FOREIGN KEY(uid)
	REFERENCES swuser(uid) 
	ON UPDATE CASCADE ON DELETE CASCADE,
	
	FOREIGN KEY(tid)
	REFERENCES time(tid) 
	ON UPDATE CASCADE ON DELETE CASCADE
);

create table dr
(
	drid		BIGINT UNSIGNED		AUTO_INCREMENT PRIMARY KEY,
	isopen		SMALLINT UNSIGNED	NOT NULL,
	uid		BIGINT UNSIGNED		NOT NULL,
	tid		BIGINT UNSIGNED		NOT NULL,

	FOREIGN KEY(uid)
	REFERENCES swuser(uid) 
	ON UPDATE CASCADE ON DELETE CASCADE,
	
	FOREIGN KEY(tid)
	REFERENCES time(tid) 
	ON UPDATE CASCADE ON DELETE CASCADE
);

create table fm
(
	fmid		BIGINT UNSIGNED		AUTO_INCREMENT PRIMARY KEY,
	speed		SMALLINT UNSIGNED	NOT NULL,
	uid		BIGINT UNSIGNED		NOT NULL,
	tid		BIGINT UNSIGNED		NOT NULL,

	FOREIGN KEY(uid)
	REFERENCES swuser(uid) 
	ON UPDATE CASCADE ON DELETE CASCADE,
	
	FOREIGN KEY(tid)
	REFERENCES time(tid) 
	ON UPDATE CASCADE ON DELETE CASCADE
);

create table rw
(
	rwid		BIGINT UNSIGNED		AUTO_INCREMENT PRIMARY KEY,
	uid		BIGINT UNSIGNED		NOT NULL,
	tid		BIGINT UNSIGNED		NOT NULL,

	FOREIGN KEY(uid)
	REFERENCES swuser(uid) 
	ON UPDATE CASCADE ON DELETE CASCADE,
	
	FOREIGN KEY(tid)
	REFERENCES time(tid) 
	ON UPDATE CASCADE ON DELETE CASCADE
);
